#!/bin/bash

# Zama Destek İçin Rapor Oluşturma Scripti
# Bu script tüm gerekli bilgileri toplar ve bir rapor dosyası oluşturur

OUTPUT_FILE="zama-support-report-$(date +%Y%m%d-%H%M%S).txt"

echo "🔍 Zama Destek Raporu Oluşturuluyor..."
echo ""

{
  echo "============================================================"
  echo "ZAMA FHE DESTEK RAPORU"
  echo "============================================================"
  echo ""
  echo "Tarih: $(date)"
  echo "Proje: ChronoMessage / SealedMessage"
  echo ""

  echo "============================================================"
  echo "1. SÖZLEŞME BİLGİLERİ"
  echo "============================================================"
  echo ""
  echo "Network: Sepolia Testnet (Chain ID: 11155111)"
  echo ""
  echo "Deploy Edilen Sözleşmeler:"
  echo "  - ConfidentialMessage: 0x38756CCb09EE1719089F370a8386a772a8F7B5cf"
  echo "  - ChronoMessageZama:   0x65016d7E35EC1830d599991d82381bf03eEC2987"
  echo ""
  echo "Deployer Address: 0xF6D39Dda8997407110264acEc6a24345834cB639"
  echo ""
  echo "Etherscan Links:"
  echo "  https://sepolia.etherscan.io/address/0x38756CCb09EE1719089F370a8386a772a8F7B5cf"
  echo "  https://sepolia.etherscan.io/address/0x65016d7E35EC1830d599991d82381bf03eEC2987"
  echo ""

  echo "============================================================"
  echo "2. SORUN TANIMI"
  echo "============================================================"
  echo ""
  echo "❌ SORUN: FHE.fromExternal() çağrıları revert ediyor"
  echo ""
  echo "Detaylar:"
  echo "  - SDK ile şifreleme başarılı"
  echo "  - Handle ve inputProof formatları doğru"
  echo "  - Gas estimation sırasında revert oluşuyor"
  echo "  - Error: execution reverted (sebep belirtilmiyor)"
  echo ""
  echo "Test Edilen Senaryolar:"
  echo "  1. ✅ SDK başlatma - Başarılı"
  echo "  2. ✅ FHE instance oluşturma - Başarılı"
  echo "  3. ✅ createEncryptedInput().encrypt() - Başarılı"
  echo "  4. ❌ sendMessage gas estimation - REVERT"
  echo "  5. ❌ EmelMarket cWETH wrap() - REVERT (karşılaştırma için)"
  echo ""

  echo "============================================================"
  echo "3. SDK KONFİGÜRASYONU"
  echo "============================================================"
  echo ""
  echo "Package: @zama-fhe/relayer-sdk v0.2.0"
  echo ""
  echo "SepoliaConfig:"
  echo "  aclContractAddress:            0x687820221192C5B662b25367F70076A37bc79b6c"
  echo "  kmsContractAddress:            0x1364cBBf2cDF5032C47d8226a6f6FBD2AFCDacAC"
  echo "  inputVerifierContractAddress:  0xbc91f3daD1A5F19F8390c400196e58073B6a0BC4"
  echo "  gatewayChainId:                55815"
  echo "  relayerUrl:                    https://relayer.testnet.zama.cloud"
  echo "  network:                       https://eth-sepolia.public.blastapi.io"
  echo ""

  echo "============================================================"
  echo "4. SÖZLEŞME KONFİGÜRASYONU"
  echo "============================================================"
  echo ""
  echo "Solidity Version: 0.8.24"
  echo "FHEVM Library: @fhevm/solidity v0.9.0-1"
  echo ""
  echo "ZamaConfig (contracts kullanıyor):"
  echo "  ACLAddress:            0x687820221192C5B662b25367F70076A37bc79b6c ✅"
  echo "  CoprocessorAddress:    0x848B0066793BcC60346Da1F49049357399B8D595"
  echo "  KMSVerifierAddress:    0x1364cBBf2cDF5032C47d8226a6f6FBD2AFCDacAC ✅"
  echo "  Protocol ID:           10001 ✅"
  echo ""
  echo "Constructor: extends SepoliaConfig"
  echo ""

  echo "============================================================"
  echo "5. TEST SONUÇLARI"
  echo "============================================================"
  echo ""
  echo "Çalıştırılan Script: scripts/verify-zama-config.ts"
  echo ""
  echo "Sonuçlar:"
  echo "  ✅ FHE Instance oluşturuldu"
  echo "  ✅ Public Key alındı (33018 bytes)"
  echo "  ✅ Sözleşme erişilebilir"
  echo "  ✅ Protocol ID doğru (10001)"
  echo "  ✅ Şifreleme başarılı"
  echo "  ✅ ACL sözleşmesi deploy edilmiş"
  echo "  ✅ Relayer erişilebilir"
  echo "  ❌ sendMessage gas estimation revert"
  echo ""
  echo "Örnek Handle: 0x1e3c63efa44a862ae503c460fc1e2982d2195493d2000000000000aa36a70500"
  echo "Handle Size: 32 bytes ✅"
  echo "Proof Size: 100 bytes ✅"
  echo ""

  echo "============================================================"
  echo "6. GEÇERLİLİK KONTROLÜ"
  echo "============================================================"
  echo ""
  echo "ACL/KMS Adres Karşılaştırması:"
  echo "  SDK ACL:       0x687820221192C5B662b25367F70076A37bc79b6c"
  echo "  Contract ACL:  0x687820221192C5B662b25367F70076A37bc79b6c"
  echo "  Durum:         ✅ EŞLEŞIYOR"
  echo ""
  echo "  SDK KMS:       0x1364cBBf2cDF5032C47d8226a6f6FBD2AFCDacAC"
  echo "  Contract KMS:  0x1364cBBf2cDF5032C47d8226a6f6FBD2AFCDacAC"
  echo "  Durum:         ✅ EŞLEŞIYOR"
  echo ""

  echo "============================================================"
  echo "7. TAHMİNİ SORUN NEDENİ"
  echo "============================================================"
  echo ""
  echo "Olası Nedenler:"
  echo ""
  echo "1. ⚠️  SÖZLEŞME KAYIT EKSİKLİĞİ"
  echo "   Sözleşmemiz Zama relayer tarafından tanınmıyor olabilir."
  echo "   Relayer'ın ACL/InputVerifier listesine eklenmemiş olabilir."
  echo ""
  echo "2. ⚠️  INPUT PROOF DOĞRULAMA SORUNU"
  echo "   createEncryptedInput(contractAddress, userAddress) çağrısı"
  echo "   doğru parametrelerle yapılıyor ancak proof doğrulanamıyor."
  echo ""
  echo "3. ⚠️  GATEWAY BAĞLANTI SORUNU"
  echo "   Gateway Chain ID: 55815"
  echo "   Sözleşme bu gateway ile iletişim kuramıyor olabilir."
  echo ""

  echo "============================================================"
  echo "8. TALEP EDİLEN DESTEK"
  echo "============================================================"
  echo ""
  echo "❓ Sorular:"
  echo ""
  echo "1. Sözleşmemiz relayer'a kayıtlı mı?"
  echo "   - Contract: 0x38756CCb09EE1719089F370a8386a772a8F7B5cf"
  echo ""
  echo "2. ACL izinleri verilmiş mi?"
  echo "   - Deployer: 0xF6D39Dda8997407110264acEc6a24345834cB639"
  echo ""
  echo "3. Input verifier sözleşmeyi biliyor mu?"
  echo "   - InputVerifier: 0xbc91f3daD1A5F19F8390c400196e58073B6a0BC4"
  echo ""
  echo "4. Sözleşmeyi manuel olarak kaydetmemiz gerekiyor mu?"
  echo ""
  echo "5. Ek bir kurulum/konfigürasyon adımı var mı?"
  echo ""

  echo "============================================================"
  echo "9. İLETİŞİM BİLGİLERİ"
  echo "============================================================"
  echo ""
  echo "Proje: ChronoMessage (Zaman Kilitli FHE Mesajlaşma)"
  echo "GitHub: (varsa eklenebilir)"
  echo ""
  echo "Deployer Email: (isteğe bağlı)"
  echo "Discord Username: (isteğe bağlı)"
  echo ""

  echo "============================================================"
  echo "10. EK DÖKÜMANLAR"
  echo "============================================================"
  echo ""
  echo "Proje içinde mevcut dökümanlar:"
  echo "  - ZAMA_TROUBLESHOOTING.md"
  echo "  - ZAMA_INTEGRATION.md"
  echo "  - scripts/verify-zama-config.ts"
  echo "  - scripts/test-emelmarket-encryption.ts"
  echo ""
  echo "Bu dosyaları da inceleyebilirsiniz."
  echo ""

  echo "============================================================"
  echo "RAPOR SONU"
  echo "============================================================"
  echo ""
  echo "Bu rapor otomatik olarak oluşturulmuştur."
  echo "Script: generate-support-report.sh"
  echo "Tarih: $(date)"
  echo ""

} > "$OUTPUT_FILE"

echo "✅ Rapor oluşturuldu: $OUTPUT_FILE"
echo ""
echo "📧 Bu raporu Zama destek ekibi ile paylaşabilirsiniz:"
echo "   - Discord: https://discord.gg/zama"
echo "   - GitHub: https://github.com/zama-ai/fhevm/issues"
echo ""
echo "📋 Rapor içeriği:"
cat "$OUTPUT_FILE"
